# Generated by Django 4.2.6 on 2023-10-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animewatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='img',
            field=models.ImageField(default='bhwbdhwb', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
